### ISSUE TITLE
Overlapping globs patterns

### ISSUE THREAD

**Issue by phisco** [neoclide/coc-yaml#1]
Is it possible to have overlapping globs patterns and specify which has to be used for a specific file afterwards? 
I've tried  this:
``` 
"yaml.schemas": {
    "kubernetes": "/*.y*ml",
    "http://json.schemastore.org/ansible-stable-2.5": "/*.y*ml"
  }
```
but coc is trying to validate a .`yml` kubernetes file using the ansible schema (probably because it's the last matching pattern declared).

**Comment by chemzqm** [comment]
I don't know, should be feature of server, refer to https://github.com/redhat-developer/yaml-language-server
