### ISSUE TITLE
Error for coc-yaml

### ISSUE THREAD

**Issue by YangKian** [neoclide/coc-yaml#14]
I install the coc-yaml extention, but when I want to add any field about yaml, such as  `yaml.trace.server` , I get the following error:

![QQ截图20200319214011](https://user-images.githubusercontent.com/45479280/77073454-43fc4b80-6a2a-11ea-9b07-b6e14b6ff8ea.png)

The CocInfo is:
> vim version: NVIM v0.4.3
node version: v12.15.0
coc.nvim version: 0.0.77-b7a597f7ae
term: xterm-256color
platform: linux

and my CocConfig file is:
![QQ图片20200319214153](https://user-images.githubusercontent.com/45479280/77073949-02b86b80-6a2b-11ea-86ad-fac4daae7e6a.png)

try to see a  CocOpenLog:
![QQ截图20200319214348](https://user-images.githubusercontent.com/45479280/77074696-2c25c700-6a2c-11ea-8bd5-0ac4904c28c4.png)

Have tried to uninstall the coc-yaml, uninstall coc-neovim and reinstall them, but none of these worked. So anything I can do to fix this?

**Comment by aca** [comment]
@YangKian 
You have to set yaml~ settings outside languageserver block.
I made the same mistake. I don't remember where did I copied it. Someone obviously post the wrong sample configuration.

**Comment by YangKian** [comment]
@aca 
You're right, it works for me now _(:з」∠)_ Thanks a lot！
