### ISSUE TITLE
Kubernetes schemas

### ISSUE THREAD

**Issue by sebiwi** [neoclide/coc-yaml#2]
Hello,

In the demo, there is a "kubernetes.yml" configuration file which allows smart completion. I can't seem to find it anywhere. In VScode, enabling it is as simple as adding this to your settings:

```
"yaml.schemas": {
  "Kubernetes": "*.yaml"
}
```
There is no Kubernetes schema in http://schemastore.org/json/. I tried using kustomization.yaml (http://json.schemastore.org/kustomization), but it doesn't work as in the demo.

Any help would be much appreciated.

**Comment by sebiwi** [comment]
I got this all wrong, sorry for the noise.

**Comment by harisund-yahoo** [comment]
@sebiwi  can you tell me what settings you configured to get the kubernetes schema working?

**Comment by wfernandes** [comment]
@hsundara I was able to get it working following https://octetz.com/docs/2020/2020-01-06-vim-k8s-yaml-support
