### ISSUE TITLE
Is it possible to override tab size as in vscode?

### ISSUE THREAD

**Issue by wayofthepie** [neoclide/coc-yaml#3]
To override the tab size the readme says:
...
 * [yaml]: VSCode-YAML adds default configuration for all yaml files. More specifically it converts tabs to spaces to ensure valid yaml, sets the tab size, and allows live typing autocompletion. These settings can be modified via the corresponding settings inside the [yaml] section in the settings:
    * editor.insertSpaces
    * editor.tabSize
    * editor.quickSuggestions

...

But when I try adding these settings at the top level I get the following:
![image](https://user-images.githubusercontent.com/1102174/67631437-6aa8c280-f88e-11e9-80c8-19073900fed7.png)

Maybe I'm just missing where this config should go :thinking: thanks.

**Comment by chemzqm** [comment]
It's shiftwidth option of your buffer.

**Comment by your-diary** [comment]
For the future readers:

Note `shiftwidth` also affects the formatter.

So, if your requirement is to make the formatter switch from 4-space indent to 2-space indent, just `set shiftwidth=2` and run the formatter.
