### ISSUE TITLE
yaml.schemaStore.enable was removed?

### ISSUE THREAD

**Issue by windowsrefund** [neoclide/coc-yaml#31]
Why was this removed in #18? According to current documentation on https://github.com/redhat-developer/yaml-language-server, this is a valid setting.

**Comment by chemzqm** [comment]
Because we have to use old yaml language server before, need add them back.

**Comment by chemzqm** [comment]
You can still add them to coc-settings.json.

**Comment by windowsrefund** [comment]
For anyone who stumbles across this, I ran a :CocUpdateSync and saw coc-yaml upgraded to 1.3.0. Once that was done, yaml.schemaStore.enable showed up in my autocomplete when edited my coc-settings.json via :CocConfig
