### ISSUE TITLE
Linting works, formatting doesn't

### ISSUE THREAD

**Issue by nathanielks** [neoclide/coc-yaml#33]
Hi @chemzqm 👋 

I'm having a similar issue as https://github.com/neoclide/coc-yaml/issues/8#issuecomment-577417621. Linting works fine, but `<Plug>(coc-format-selected)` doesn't do anything. When I look at `:CocOpenLog`, the following log entry sticks out to me:

```
2021-01-02T23:58:52.962 WARN (pid:55705) [handler-format] - format provider not found!
```

I also have formatting enabled in `coc-settings.json`. Is there anything else I can do to help you figure this out?

**Comment by chemzqm** [comment]
The language server doesn't have support for range format.

**Comment by nathanielks** [comment]
Noted, thank you @chemzqm
