### ISSUE TITLE
YAML files inside a dir named tasks are incorrectly parsed

### ISSUE THREAD

**Issue by taylorsilva** [neoclide/coc-yaml#34]
neovim: v0.4.4

Any yaml files that I put inside a directory called `tasks` are incorrectly parsed by coc-yaml. I confirmed this by removing coc-yaml and I no longer got the syntax error popping up.

```
Incorrect type. Expected "array".
[yaml-schema: Ansible 2.9:]
```

I have no clue if Ansible is at all relevant to the problem. I don't use ansible or have any of it's related apps installed on my system.

My file.yaml
```yaml
some: value
keys: 123
lists:
  - item1
  - item2

maps_here:
  thing: here
  other: thing here
```

### Expected Results

YAML files are correctly parsed.

### Actual Results
The yaml file inside `tasks` is incorrectly parsed. Files inside any other dir are correctly parsed.
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/4583837/105609672-d838ec80-5d78-11eb-9029-caa96255d108.png">

After removing coc-yaml
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/4583837/105609817-d0c61300-5d79-11eb-9efe-6fdab9fcbf64.png">

**Comment by chemzqm** [comment]
It's caused by https://www.schemastore.org/api/json/catalog.json, use `yaml.schemas` configuration to override it.
