### ISSUE TITLE
incorrect lint on github actions' workflow

### ISSUE THREAD

**Issue by 0x8f701** [neoclide/coc-yaml#40]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/33961674/118966527-67a78280-b99c-11eb-83dc-cb0c574d0843.png">
sometimes I can get incorrect lint on some github actions workflows like:

https://github.com/parallel-finance/parallel/blob/master/.github/workflows/deploy.yml#L1-L7

**Comment by 0x8f701** [comment]
if I remove the first seven lines then paste back and save, then the errors move down:

<img width="558" alt="image" src="https://user-images.githubusercontent.com/33961674/120344860-8e66a100-c32c-11eb-904d-1ba322e5c463.png">

**Comment by timtyrrell** [comment]
Yeah, getting:
`[yaml-schema: https://json.schemastore.org/github-workflow.json] [E] Missing property "jobs"`

I totally have a `jobs` property in there.

EDIT: ah, sounds related to this issue: https://github.com/neoclide/coc-yaml/issues/28#issuecomment-784849086

**Comment by chemzqm** [comment]
Use `:CocCommand yaml.selectSchema` to choose yaml schema.
