### ISSUE TITLE
Kustomize schemas getting ignored.

### ISSUE THREAD

**Issue by pslobo** [neoclide/coc-yaml#41]
It seems as though the kustomization schema is being totally ignored. Below is a valid `kustomization.yaml` (but with errors highlighted):

```yaml
>>apiVersion: kustomize.config.k8s.io/v1beta1
>>kind: Kustomization

  resources:
>>  - deployment.yaml
>>  - pdb.yaml
>>  - service.yaml
>>  - serviceaccount.yaml

>>commonLabels:
    app.kubernetes.io/component: swagger-apis
    app.kubernetes.io/name: swagger-apis
    app.kubernetes.io/part-of: service1
```

Hovering over the errors, I get stuff like:
```yaml
[yaml-schema: https://raw.githubusercontent.com/instrumenta/kubernetes-json-schema/master/v1.17.0-standalone-strict/_definitions.json] \
[E] Missing property "groupVersion"
```

We can see it's targeting the Kubernetes schema even though I specified another schema. If I remove reference to Kubernetes schema,  then it works as expected. Initially I thought it was something I was doing wrong and it didn't respect precedence, but it works as expected for other schemas such as `docker-compose` or `circleconfig`. This is my `cog-settings.json` so far.

```json
{
  "languageserver": {
      "golang": {
        "command": "gopls",
        "rootPatterns": ["go.mod"],
        "filetypes": ["go"]
      },

      "terraform": {
        "command": "terraform-ls",
        "filetypes": ["terraform", "tf"]
      }
  },

  "yaml.format.enable": true,
  "yaml.schemas": {
      "kubernetes": "/*.yaml",
      "https://json.schemastore.org/kustomization.json": "/kustomization.yaml",
      "https://json.schemastore.org/circleciconfig.json": ".circleci/config.yaml",
      "https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json": "/docker-compose.ya?ml"
  },

    "coc.preferences.extensionUpdateCheck": "daily"
}
```

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Try command `:CocCommand yaml.selectSchema` to select schema.
