### ISSUE TITLE
Crashes immediately after updating to 1.4.1

### ISSUE THREAD

**Issue by IngoMeyer441** [neoclide/coc-yaml#42]
Hey and thanks for all your work on coc.nvim and all the useful extensions! :smiley: 
After updating `coc-yaml` to version 1.4.1 I always get a server crash when `coc-yaml` is activated:

```
TypeError: Cannot read property 'length' of undefined
    at SettingsHandler.setConfiguration (/home/imeyer/.config/coc/extensions/node_modules/coc-yaml/node_modules/yaml-language-server/out/server/src/languageserver/handlers/settingsHandlers.js:79:51)
    at SettingsHandler.<anonymous> (/home/imeyer/.config/coc/extensions/node_modules/coc-yaml/node_modules/yaml-language-server/out/server/src/languageserver/handlers/settingsHandlers.js:56:18)
    at Generator.next (<anonymous>)
    at fulfilled (/home/imeyer/.config/coc/extensions/node_modules/coc-yaml/node_modules/yaml-language-server/out/server/src/languageserver/handlers/settingsHandlers.js:5:58)
[Info  - 9:16:12 AM] Connection to server got closed. Server will restart.
/home/imeyer/.config/coc/extensions/node_modules/coc-yaml/node_modules/yaml-language-server/out/server/src/languageserver/handlers/settingsHandlers.js:79
                if (settings.yaml.schemaStore.url.length !== 0) {
                                                  ^
```

I am on a Linux box with the latest `coc.nvim` version.

**Comment by chemzqm** [comment]
Unable to reproduce, seems you have bad configuration.

**Comment by IngoMeyer441** [comment]
I use the default configuration for yaml (there are no configuration entries for yaml in my `coc-settings.json`). Seems that `coc-yaml` expects an url configuration for the schema store. If I add
```json
    "yaml.schemaStore.url": "",
```
for testing to my `coc-settings.json`, crashes do not happen.

**Comment by AtomicMegaNerd** [comment]
I was having the crash on coc-yaml 1.4.0 and 1.4.1.  The above workaround works.  Adding the blank yaml.schemaStore.url property to my coc-settings.json fixed the crashes for me.  This was crashing on 3 different machines that I operate (1 Linux and two MacOS).  I am running neovim 0.5 stable:

> uname -a
Darwin Roflania 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

> node --version
v16.4.2

[init.vim.txt](https://github.com/neoclide/coc-yaml/files/6770243/init.vim.txt)
[coc-settings.json.txt](https://github.com/neoclide/coc-yaml/files/6770244/coc-settings.json.txt)

I do use homebrew on all three with Node 16, I didn't test on Node 14 LTS.

**Comment by nemonik** [comment]
On OSX one gets yaml server errors @IngoMeyer441's describes... Same exact config on Arch Linux works perfectly editing the same exact ansible yaml file.

**Comment by nemonik** [comment]
copying @Frederick888's "yaml.schemaStore.url" from the above commit into my coc-settings.json fixed things for me... so, yep... thank you sir.

https://github.com/Frederick888/coc-yaml/commit/6512eded86b71809dcaa536c434ee77cbe8ea2cd

**Comment by augustocdias** [comment]
I have only theses settings and it is crashing for me too:

```json
  "yaml.schemas": {
    "https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json": ["/*.yaml", "/*.yml"]
  },
  "yaml.format.enable": true,
```
