### ISSUE TITLE
[coc.nvim]: Error on "jumpImplementation": implementation provider not found for current buffer, your language server doesn't support it.

### ISSUE THREAD

**Issue by 0x8f701** [neoclide/coc-yaml#44]
it seems that I start to have this problem after upgrading, do you have an idea on this?

**Comment by chemzqm** [comment]
Your language server doesn't support it.

**Comment by 0x8f701** [comment]
@chemzqm can this be hided by coc.nvim? because I can image that different language server has different implmentations and missing features

**Comment by chemzqm** [comment]
No, it's intended to be shown, you can use `silent! call CocAction('jumpImplementation')` to hide errors.
