### ISSUE TITLE
Can't configure with Kubernetes schema

### ISSUE THREAD

**Issue by pilot513** [neoclide/coc-yaml#47]
Hello.
Can't configure with Kubernetes schema.

In config (CocConfig) set:
`
$ cat ~/.vim/coc-settings.json
{
  "yaml.trace.server": "verbose",
  "python.linting.flake8Enabled": true,
  "python.linting.enabled": true,
  "yaml.format.enable": true,
  "yaml.validate": true,
  "json.format.enable": true,
  "yaml.schemas": {
    "kubernetes": ["/*.yaml"]
  }
}
`
## versions

`
vim version: VIM - Vi IMproved 8.1 8012269
node version: v12.22.6
coc.nvim version: 0.0.80-daab29410d
coc.nvim directory: /home/pilot/.vim/plugged/coc.nvim
term: dumb
platform: linux

## Log of coc.nvim

2021-09-02T09:13:41.354 INFO (pid:1898) [plugin] - coc.nvim 0.0.80-daab29410d initialized with node: v12.22.6 after 73ms
2021-09-02T09:13:44.964 INFO (pid:1898) [attach] - receive notification: showInfo []
`

CocTrace:
`[Trace - 9:19:23] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "yaml": {
            "execArgv": [],
            "trace": {
                "server": "verbose"
            },
            "schemas": {
                "kubernetes": [
                    "/*.yaml"
                ]
            },
            "format": {
                "enable": true,
                "singleQuote": false,
                "bracketSpacing": true,
                "proseWrap": "preserve",
                "printWidth": 80
            },
            "validate": true,
            "hover": true,
            "completion": true,
            "customTags": [],
            "schemaStore": {
                "enable": true,
                "url": "https://www.schemastore.org/api/json/catalog.json"
            },
            "disableAdditionalProperties": false,
            "maxItemsComputed": 5000
        },
        "http": {
            "proxyStrictSSL": true
        },
        "[yaml]": {}
    }
}
`
What am I doing wrong? Can you help me, please

**Comment by pilot513** [comment]
Sorry, I didn't notice that "* .yaml" # "*. yml"

Tell me, is it possible to force both types of files to be processed?
How can I explicitly specify the version of k8s (eg 1.19)?

Another question is, how can you simultaneously specify a schema for working with Ansible roles?
I found themas: 
https://json.schemastore.org/ansible-role-2.9.json
https://json.schemastore.org/ansible-playbook.json
https://json.schemastore.org/ansible-inventory.json

but I don't understand how they can be specified to work simultaneously with k8s.

**Comment by chemzqm** [comment]
Use `"yaml.schemas": { "kubernetes": ["/*.yaml", "/*.yml"] }`

**Comment by chemzqm** [comment]
> but I don't understand how they can be specified to work simultaneously with k8s.

Can't understand your question.
