### ISSUE TITLE
cannot be installed 

### ISSUE THREAD

**Issue by ta3pks** [neoclide/coc-yaml#53]
![image](https://user-images.githubusercontent.com/9097437/146598398-3d1afa0c-7fcc-4927-bce1-c3d3efb537d9.png)

**Comment by chemzqm** [comment]
Checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by ta3pks** [comment]
I dont understand why would you close a bug report while the bug still exists

**Comment by chemzqm** [comment]
Can't help.
