### ISSUE TITLE
Feature request: load/merge settings.json from current directory

### ISSUE THREAD

**Issue by jaypikay** [neoclide/coc-yaml#55]
It would be nice to have, if coc-yaml would load and merge the yaml.schemas from within the current working directory. I work on a project where we use custom schemas for yaml files. VSCode loads the schemas from the local directory `.vscode/settings.json` where.

Providing a option to enable and configure local project configuration would be great.

**Comment by chemzqm** [comment]
You can use  `yaml.schemas` in your `.vim/coc-settings.json`

**Comment by jaypikay** [comment]
I know, but if you have a coliding filenames with different schemas, you need to edit it again. And when switching back to the other project, you need to edit it again. IMHO having something like local vimrc, but for coc-settings, would be a lot easier.
