### ISSUE TITLE
Property DeletionPolicy is not allowed

### ISSUE THREAD

**Issue by fdaciuk** [neoclide/coc-yaml#56]
Hey! Thanks for this extension!
I'm having some troubles when I try to write a yml for serverless framework.
I receive the error `Property DeletionPolicy is not allowed`, but the configuration [is correct](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html).

![Screenshot from 2022-03-05 17-12-46](https://user-images.githubusercontent.com/487669/156898686-61505a31-1db6-4627-8ef6-6da4bbe110c2.png)

Can you see if I'm doing something wrong?

**Comment by chemzqm** [comment]
You may need `yaml.selectSchema` to change schema for current file, or you may need to fix the schema url https://github.com/neoclide/coc-yaml/blob/master/Readme.md#associating-schemas

**Comment by fdaciuk** [comment]
Hey @chemzqm! I just need to find out the right schema, but that was helpful. Thanks!
