### ISSUE TITLE
about docker-compose.yml

### ISSUE THREAD

**Issue by akiooo45** [neoclide/coc-yaml#67]
When I edit the docker-compose.yml file, it cannot be completed normally, starting from the third line of image
![image](https://user-images.githubusercontent.com/79924166/185532443-743db4c9-856e-40e6-9e02-19fbdba26f6a.png)

**Comment by chemzqm** [comment]
You may need use `:CocCommand yaml.selectSchema`

**Comment by akiooo45** [comment]
then,what I need
![image](https://user-images.githubusercontent.com/79924166/185567254-1df81de1-31d6-42db-948f-5207537a32eb.png)
