### ISSUE TITLE
Show type in hover

### ISSUE THREAD

**Issue by RedBeard0531** [neoclide/coc-yaml#70]
This would be especially helpful for enums to list the valid options. Might also be nice to show properties of objects.

**Comment by chemzqm** [comment]
`:h CocAction('definitionHover')` might helps.

**Comment by RedBeard0531** [comment]
I'm not seeing any difference with `'definitionHover'` vs `'doHover'`

**Comment by chemzqm** [comment]
Should be problem of your language server, checkout https://github.com/neoclide/coc.nvim/wiki/Debug-language-server#using-output-channel

**Comment by chemzqm** [comment]
Seems you need send feature request to yaml-languageserver
