### ISSUE TITLE
How to disable "yaml.validate" for a particular folder as opposed to globally?

### ISSUE THREAD

**Issue by V4G4X** [neoclide/coc-yaml#77]
I have a workspace where the the YAML files involved are cloudformation templates, and they are validated by `cfn-lint`.  
Only for this workspace I want most features from the yaml lsp like formatting etc. Just not the validation. 

So I disabled validation using `yaml.validate`.

But in another workspace where I use OpenAPI spec yamls, they stopped getting validated. I still need validation for those. 

Is it possible to get folder-specific configurations?

**Comment by chemzqm** [comment]
Sure, see `:h coc-configuration-scope`
