### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by utrumo** [neoclide/coc-yaml#8]
CocInstall coc-yaml
My coc-settings.json:
```
{
  "yaml.trace.server": "verbose",
  "yaml.schemas": {
    "http://json.schemastore.org/ansible-stable-2.7": "*"
  }
}
```
:CocOpenLog:
```
2020-01-22T13:21:10.633 INFO (pid:29611) [services] - registered service "diagnostic-languageserver"
2020-01-22T13:21:10.669 INFO (pid:29611) [services] - registered service "eslint"
2020-01-22T13:21:10.683 INFO (pid:29611) [services] - registered service "highlight"
2020-01-22T13:21:10.693 INFO (pid:29611) [language-client-index] - highlight started with 29654
2020-01-22T13:21:10.701 INFO (pid:29611) [plugin] - coc 0.0.74-db5ffd2ff0 initialized with node: v13.7.0
2020-01-22T13:21:10.774 INFO (pid:29611) [services] - highlight server state change: starting => running
```
Nothing happen When i trying  to open any of *.yml files except yaml.ansible extension in status bar.

**Comment by chemzqm** [comment]
Make sure your filetype is yaml

**Comment by utrumo** [comment]
Yes. If my yaml file called `main.yml` or has in head `#!/usr/bin/env ansible-playbook`:
my neovim detects filtype as `yaml.ansible`. This behavior  breaks work coc-yaml.

Temporary fix is - `:set filetype=yaml`

Can you add support yaml.* filetype extensions and vim filetype instead of globPattern in coc config?
yaml.schemas: {
    "url": "neovimFiletype"
}

There is example:
yaml.schemas: {
  "http://json.schemastore.org/ansible-stable-2.7": "yaml.ansible"
}

**Comment by chemzqm** [comment]
Checkout `:h g:coc_filetype_map`

**Comment by utrumo** [comment]
> Checkout `:h g:coc_filetype_map`

~~This option doesn't work in any place of my vimrc:~~
 ```
  let g:coc_filetype_map = {
  \ 'yaml.ansible': 'yaml',
  \ }
```
updated:
With coc_filetype_map now all working and loading correct theme automatically without any additional settings.
Not working format section: double quotes doesn't changing on single. Not automatic and not with <leader>f hotkey
part of .vimrc:
```
" Remap for format selected region
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)
```
In coc-seettings.json i simple added only:
```
  "yaml.format.enable": true,
  "yaml.format.singleQuote": true,
  "yaml.trace.server": "verbose",
```
part of trace:
```
[Trace - 11:32:52 AM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "yaml": {
            "execArgv": [],
            "trace": {
                "server": "verbose"
            },
            "schemas": {},
            "format": {
                "enable": true,
                "singleQuote": true,
                "bracketSpacing": true,
                "proseWrap": "preserve"
            },
            "validate": true,
            "hover": true,
            "completion": true,
            "customTags": []
        },
        "http": {
            "proxyStrictSSL": true
        }
    }
}
```
